[project]
name = "server-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "hf-xet>=1.2.0",
    "optimum>=2.0.0",
    "transformers>=4.57.1",
    "scipy",
    "flask-cors>=6.0.1",
]
